name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: arikchakma/workflows/.github/workflows/release-bun.yml@v1
    with:
      publish: true
      build: bun run build
    permissions:
      contents: write
      id-token: write
    secrets: inherit
