name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: arikchakma/workflows/.github/workflows/release-pnpm.yml@v1
    with:
      publish: true
      build: pnpm run build
    secrets: inherit
